### ISSUE TITLE
snap.snapd-desktop-integration.snapd-desktop-integration.service fails to start during boot

### ISSUE THREAD

**Issue by slovdahl** [snapcore/snapd-desktop-integration#23]
`snap.snapd-desktop-integration.snapd-desktop-integration.service` fails to start during boot for me with the following being logged:

```
okt 03 20:29:35 desk snapd-desktop-integration.snapd-desktop-integration[5208]: Sorry, home directories outside of /home are not currently supported.
okt 03 20:29:35 desk snapd-desktop-integration.snapd-desktop-integration[5208]: See https://forum.snapcraft.io/t/11209 for details.
okt 03 20:29:35 desk systemd[4860]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Main process exited, code=exited, status=1/FAILURE
okt 03 20:29:35 desk systemd[4860]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Failed with result 'exit-code'.
```

I'm not sure if I'm having any issues caused by this, but was advised to [log an issue](https://discourse.ubuntu.com/t/call-for-testing-native-messaging-support-in-the-firefox-snap/29759/94?u=slovdahl) for it anyway. My installation is upgraded from Ubuntu 20.04 (and possibly from 18.04 before that, can't recall).

I saw #12, but none of the steps the author of that issue took has fixed it for me. What can I do to help pinpointing the issue?

**Comment by slovdahl** [comment]
I think I'm on the latest version:

```
$ snap list snapd-desktop-integration 
Name                       Version  Rev  Tracking       Publisher   Notes
snapd-desktop-integration  0.1      14   latest/stable  canonical✓  -
$ sudo snap refresh snapd-desktop-integration 
snap "snapd-desktop-integration" has no available updates
```

**Comment by sergio-costas** [comment]
Mmm... very odd... Can you try to uninstall it and reinstall?

    sudo snap remove --purge snapd-desktop-integration
    sudo snap install snapd-desktop-integration

**Comment by slovdahl** [comment]
```
$ sudo snap remove --purge snapd-desktop-integration
snapd-desktop-integration removed
$ sudo snap install snapd-desktop-integration
snapd-desktop-integration 0.1 from Canonical✓ installed
```

and after rebooting:

```
$ sudo journalctl -b | grep snapd-desktop-integration
okt 07 08:14:33 desk systemd[1]: Mounting Mount unit for snapd-desktop-integration, revision 14...
okt 07 08:14:33 desk systemd[1]: Mounted Mount unit for snapd-desktop-integration, revision 14.
okt 07 08:14:33 desk audit[1209]: AVC apparmor="STATUS" operation="profile_load" profile="unconfined" name="snap-update-ns.snapd-desktop-integration" pid=1209 comm="apparmor_parser"
okt 07 08:14:33 desk audit[1266]: AVC apparmor="STATUS" operation="profile_load" profile="unconfined" name="snap.snapd-desktop-integration.hook.configure" pid=1266 comm="apparmor_parser"
okt 07 08:14:33 desk audit[1267]: AVC apparmor="STATUS" operation="profile_load" profile="unconfined" name="snap.snapd-desktop-integration.snapd-desktop-integration" pid=1267 comm="apparmor_parser"
okt 07 08:14:41 desk systemd[4947]: Started Service for snap application snapd-desktop-integration.snapd-desktop-integration.
okt 07 08:14:41 desk dbus-daemon[4981]: [session uid=127 pid=4981] Activating via systemd: service name='org.freedesktop.portal.Documents' unit='xdg-document-portal.service' requested by ':1.1' (uid=127 pid=4962 comm="/usr/bin/snap run snapd-desktop-integration ")
okt 07 08:14:41 desk snapd-desktop-integration.snapd-desktop-integration[4962]: Sorry, home directories outside of /home are not currently supported.
okt 07 08:14:41 desk snapd-desktop-integration.snapd-desktop-integration[4962]: See https://forum.snapcraft.io/t/11209 for details.
okt 07 08:14:41 desk systemd[4947]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Main process exited, code=exited, status=1/FAILURE
okt 07 08:14:41 desk systemd[4947]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Failed with result 'exit-code'.
```

**Comment by sergio-costas** [comment]
Mmmm... "Sorry, home directories outside of /home are not currently supported."

That's odd... have you moved your home folder outside /home?

**Comment by sergio-costas** [comment]
There are extra info about how to proceed in that case here: https://forum.snapcraft.io/t/support-for-non-home-homedirs/11209/11

**Comment by slovdahl** [comment]
> That's odd... have you moved your home folder outside /home?

Nope, nothing out of the ordinary, my own user's home directory is `/home/slovdahl`. There are two or three other "normal" users too, but they are in `/home` too.

**Comment by sergio-costas** [comment]
Mmm...

Can you open your /etc/passwd file and check if any of the entries have an user with an UID equal or greater than 1000 and a home folder pointing to something different to /home/XXX?

(but don't paste the file here)

**Comment by slovdahl** [comment]
Hm, I looked before but didn't realize this one exists:

```
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
```

**Comment by sergio-costas** [comment]
Nah... I have that one too...

**Comment by sergio-costas** [comment]
What happens if you run it manually? I mean:

    /snap/snapd-desktop-integration/current/bin/snapd-desktop-integration

**Comment by slovdahl** [comment]
It doesn't fail at least:

```
$ /snap/snapd-desktop-integration/current/bin/snapd-desktop-integration 
** Message: 12:38:22.011: New theme: gtk=Yaru-dark icon=Yaru cursor=Yaru, sound=Yaru
All available theme snaps installed
```

And then it just keeps running without outputting anything.

**Comment by sergio-costas** [comment]
And if you run from inside the container?

    snap run snapd-desktop-integration

**Comment by slovdahl** [comment]
Same behaviour:

```
$ snap run snapd-desktop-integration
** Message: 12:52:58.992: New theme: gtk=Yaru-dark icon=Yaru cursor=Yaru, sound=Yaru
All available theme snaps installed

```

**Comment by sergio-costas** [comment]
Ok... then the bug isn't here, in snapd-desktop-integration, but it seems that it is in snapd itself...

**Comment by slovdahl** [comment]
Ok. Happy to help testing things if it can help us pinpoint the issue.

**Comment by sergio-costas** [comment]
Thank you!

**Comment by sergio-costas** [comment]
Just another question: which version of snapd do you have?

**Comment by Dan-Master** [comment]
> Just another question: which version of snapd do you have?

I seem to have run into the same problem on Ubuntu 22.04.1 LTS and have been trying to fix it for a week without success. 
I noticed this on Oct 22 when I turned on my laptop and started Chromium (using GTK+ theme) which always had a dark design theme in line with the system theme, but then suddenly it had a white appearance. In the same way some other Snap applications also turned white or no longer work, although those that are installed via .deb or Flatpak seem to work without problems. I looked at the log history and the only thing that was installed the day before was the snapd update.

TStart-Date: 2022-10-21  04:20:28
Commandline: packagekit role='update-packages'
Upgrade: snapd:amd64 (2.56.2+22.04ubuntu1, 2.57.4+22.04)
End-Date: 2022-10-21  04:21:04

**Comment by sergio-costas** [comment]
No, no... I need you to run "snap list snapd" from a command line. Snapd is updated as a snap, no matter if you have a different .deb package installed.

**Comment by Dan-Master** [comment]
> No, no... I need you to run "snap list snapd" from a command line. Snapd is updated as a snap, no matter if you have a different .deb package installed.

snapd     2.57.4  17336   latest/stable  canonical✓  snapd

**Comment by JackDuchamFF** [comment]
I found this thread while I was investigating a similar message in Logs. 
Sender: `systemd`
Message: `Failed to start Service for snap application snapd-desktop-integration.snapd-desktop-integration `
Subject: `A start job for unit UNIT has failed`

Following the steps listed further up:
`sudo snap refresh snapd-desktop-integration` gives
`snap "snapd-desktop-integration" has no updates available`

There are three (human) users with UIDs >= 1000, but all three of them have their home directory in the usual place (`/home/{some_dir}`).

Interestingly, `snap list snapd` gives
`error: no matching snaps installed`

I haven't done any customization with themes or touched snap at all (to my knowledge), other than using it through the Ubuntu Software GUI to install Firefox. I just noticed the message while I was looking into something else.
OS Name: `Ubuntu 22.04.1 LTS`

**Comment by Dan-Master** [comment]
UPD. snapd  2.57.5  17576   latest/stable  canonical✓  snapd  OS: Ubuntu 22.04.1 LTS

Yesterday I got the snapd update to version 2.57.5 (17576), after rebooting everything that was broken on 2.57.4 (17336) is fixed.
The dark themes in snap apps (e.g. Chromium) are back where they should be, and also other snap apps like todoist and translatium, which were broken before, started to run.
This is of course good news, but I have already moved almost all of my snap apps to flatpak.

And yes, I also see error messages in the log: 
Failed to start Service for snap application snapd-desktop-integration.snapd-desktop-integration. 
Failed to start Application launched by gnome-session-binary. 
But it doesn't seem to have any effect on operability.

**Comment by dellgreen** [comment]
Seeing ii also in my 22.04.1 LTS, removed snapd-desktop-integration in the end for the time being

`snapd  2.57.6   17883  latest/stable  canonical✓  snapd`

**Comment by sergio-costas** [comment]
Ok, the error message is normal, and should be "not problematic": it's because the daemon is being launched at the same time than the desktop, and sometimes it is "too early" and can't connect into it; but it is relaunched two second after that, and then it would work fine (if it is still too early, it will be relaunched again two seconds after...).

**Comment by EML-github** [comment]
But I'm getting this error message *every* 2 seconds in syslog; it's restarting indefinitely. This started on an upgrade from Ubuntu 20.04 to 22.04.1; snapd v2.57.6. I have 5 users at or above uid 1000: myself and vmail, both in /home, and nobody, snapd-range-524288-root, and snap_daemon, all in /nonexistent. Would any more information be useful? 

```
# snap list snapd
Name   Version  Rev    Tracking       Publisher   Notes
snapd  2.57.6   17883  latest/stable  canonical✓  snapd
```

**Comment by sergio-costas** [comment]
Oh, ok... that's a different problem: currently, due to some limitations in snapd, snapd-desktop-integration is launched in any session, not only in graphical ones, and, as you can imagine, they will fail in those cases. That's why they keep relaunching.

We are already working on both the right solution(tm), which will require some time because it will require modifying snapd, and a quick fix to avoid these messages in the meantime.

**Comment by EML-github** [comment]
Ok, thanks. Unfortunately, this also happens when running over vnc. However, I can confirm that the restarts stop if I kill vncserver, find the physical computer, plug a monitor on to it, and log in. Short term, I'm  afraid that I've removed `snapd-desktop-integration` to get around this.

**Comment by j75** [comment]
I am also on Ubuntu 22.04.1 and it also filled /var/log/messages with messages like
```
snap.snapd-desktop-integration.snapd-desktop-integration.service: Scheduled restart job, restart counter is at 316.
ERROR: not connected to the gnome-3-38-2004 content interface.
```
Running manually `snap run snapd-desktop-integration` displayed
```
Gtk-Message: 10:29:17.044: Failed to load module "xapp-gtk3-module"
Gtk-Message: 10:29:17.044: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
```

**Comment by rokj** [comment]
I am seeing a lot of 
```
Dec  4 13:45:32 buro systemd[1735]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Scheduled restart job, restart counter is at 24368.
Dec  4 13:45:32 buro systemd[1735]: Stopped Service for snap application snapd-desktop-integration.snapd-desktop-integration.
Dec  4 13:45:32 buro systemd[1735]: Started Service for snap application snapd-desktop-integration.snapd-desktop-integration.
Dec  4 13:45:32 buro snapd-desktop-i[1616378]: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
```

also.

**Comment by jdchristensen** [comment]
There are at least two discussions about the atk-bridge issue on AskUbuntu.  Here's the one with the most comments:  https://askubuntu.com/questions/1443676/snapd-desktop-integration-syslog-spam/1443857
We're seeing those lines in our logs every two seconds.  It may have to do with ssh connections, which have no graphical environment, but it continues to happen on my machine when a user is also logged into a desktop environment.

**Comment by thinkjrs** [comment]
I am also experiencing issues related to what's been shared herein. 

That said, rather than pile on, here are two launchpad (Ubuntu) issues potentially related, in case that helps marry together information and some coredumps:

- [1983192](https://bugs.launchpad.net/snapd-desktop-integration/+bug/1983192)
- [1951491](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1951491)

**Comment by sergio-costas** [comment]
Ok, this error should be fixed partly in the current stable (it won't show anymore errors from the GDM session), and completely in the candidate (it won't show errors neither from GDM, nor from SSH sessions).

**Comment by hickst** [comment]
@sergio-costas Where is the correct place to report the unresolved issue of ssh-triggered syslog messages? This are still happening with snapd-desktop-integration:0.1 rev 49 which is listed as "latest/stable". If this issue has been resolved in a later release, please provide instructions to upgrade. Thanks.

**Comment by sergio-costas** [comment]
@hickst All these problems have been fixed with the last merges. You can install the "latest/candidate" version, but to make it fully functional you must manually connect the login-session-observe plug ( sudo snap connect snapd-desktop-integration:login-session-observe ).

**Comment by sergio-costas** [comment]
That connection will be automatic when that version is moved into stable.

**Comment by sergio-costas** [comment]
@Dan-Master Can you try to launch one of those applications that won't start from a command line with:

    snap run application-name

and paste here the error message shown in the screen?

**Comment by sergio-costas** [comment]
(anyway, remember that this is "snapd-desktop-integration", not "snapd")

**Comment by Dan-Master** [comment]
@sergio-costas Most of my critical applications have been converted to flatpak since the problem started last time, but here are a couple of examples of snap-apps that I still have and won't run now:

```
$ snap run todoist
/snap/todoist/841/todoist: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
$ snap run clipto
/snap/clipto/22/clipto: error while loading shared libraries: libxshmfence.so.1: cannot open shared object file: No such file or directory

```
I'll also add the error messages I see in the logs:

```
17:39:49 gdm-session-wor: GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
17:39:30 systemd: Failed to start Application launched by gnome-session-binary.
17:39:27 gdm-session-wor: gkr-pam: unable to locate daemon control file
17:39:16 gnome-session-b: GLib-GIO-CRITICAL: g_bus_get_sync: assertion 'error == NULL || *error == NULL' failed
17:39:16 gnome-session-b: GLib-GIO-CRITICAL: g_bus_get_sync: assertion 'error == NULL || *error == NULL' failed
17:39:16 gnome-session-b: GLib-GIO-CRITICAL: g_bus_get_sync: assertion 'error == NULL || *error == NULL' failed
17:39:15 canonical-livep: Task "refresh" returned an error: livepatch check failed: POST request to "https://livepatch.canonical.com/v1/client/f578fb05620144879bd62b904fbc5914/updates" failed, retrying in 30s.
```

**Comment by sergio-costas** [comment]
Mmm... that's an odd message... It's like the gnome snap isn't installed.

Do you have installed gnome-3-28-1804? Can you check if those packages have the gnome plug connected to that package? (for this last thing, run "snap connections package-name")

**Comment by Dan-Master** [comment]
> Mmm... that's an odd message... It's like the gnome snap isn't installed.
> 
> Do you have installed gnome-3-28-1804? Can you check if those packages have the gnome plug connected to that package? (for this last thing, run "snap connections package-name")

Excerpt from snap list

```
gnome-3-28-1804                       3.28.0-19-g98f9e67.98f9e67  161     latest/stable    canonical✓        -
gnome-3-34-1804                       0+git.3556cb3               77      latest/stable    canonical✓        -
gnome-3-38-2004                       0+git.6f39565               119     latest/stable    canonical✓        -
gnome-42-2204                         0+git.0c1a50b               56      latest/stable    canonical✓        -
```
Here is an example of Translatium, which does not even start forcibly, despite the fact that it is added to the autorun

```
$ snap connections translatium
Interface                 Plug                         Slot                             Notes
audio-playback            translatium:audio-playback   :audio-playback                  -
browser-support           translatium:browser-support  :browser-support                 -
content[gnome-3-28-1804]  translatium:gnome-3-28-1804  gnome-3-28-1804:gnome-3-28-1804  -
content[gtk-3-themes]     translatium:gtk-3-themes     gtk-common-themes:gtk-3-themes   -
content[icon-themes]      translatium:icon-themes      gtk-common-themes:icon-themes    -
content[sound-themes]     translatium:sound-themes     gtk-common-themes:sound-themes   -
desktop                   translatium:desktop          :desktop                         -
desktop-legacy            translatium:desktop-legacy   :desktop-legacy                  -
gsettings                 translatium:gsettings        :gsettings                       -
home                      translatium:home             :home                            -
network                   translatium:network          :network                         -
opengl                    translatium:opengl           :opengl                          -
pulseaudio                translatium:pulseaudio       :pulseaudio                      -
unity7                    translatium:unity7           :unity7                          -
wayland                   translatium:wayland          :wayland                         -
x11                       translatium:x11              :x11                             -
```

**Comment by sergio-costas** [comment]
I installed those two programs and they do work fine... Can you try to uninstall and reinstall them?

**Comment by Dan-Master** [comment]
> I installed those two programs and they do work fine... Can you try to uninstall and reinstall them?

So, on your recommendation, I reinstalled several applications to check: clipto, translatium and todoist.
To my surprise, they run now, but if you do it with a command in the terminal, in each case an error is displayed along with the start of the application:

```
$ snap run snap-store
19:26:15:0350 Gtk Failed to load module "xapp-gtk3-module"
```

This seems to be the reason why snap-store is now only displayed in a light color scheme, despite the dark theme globally installed on the system.
And the most unpleasant thing for my eyes is that Chromium (with the GTK+ theme selected) is only displayed in white. I can of course reinstall Chromium to Flatpak, but I already have several PWA applications installed that depend on Snap-Chromium + in addition I have several extensions with fine-tuning that I spent a lot of time on, I don't want to reconfigure everything again.
Any ideas on how to fix the dark theme in snap without reinstalling Chromium?)

**Comment by sergio-costas** [comment]
Do you have a theme different than the default one? Which one? (to do tests)

**Comment by Dan-Master** [comment]
> Do you have a theme different than the default one? Which one? (to do tests)

No third-party themes are installed, I use the standard Yaru-Dark. Let me tell you right away that I have already tried to manually activate the Yaru-Dark theme for applications through the User Themes extension with Gnome tweaks. Thus, the global theme changes, exactly as well as through the system settings, but in Chromium and SnapStore remains invariably light. I also note that above the active elements of the browser pages that have a hyperlink, I now see the outdated cursor in the form of a hand, rather than the system cursor in the form of an arrow.

I have a feeling that Chromium doesn't see which theme is used globally by the system, and since this problem occurred again after the update to snapd 2.58 (17950) I assume that either some dependencies were broken or no appropriate attributes for sandboxing shared libraries were provided. 
Just in case, I will add an error log that is visible if you run Chromium through the terminal:

<details>
<summary>Chromium log</summary>

```
$ snap run chromium
update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/usr/share/gimp/2.0/help /usr/share/gimp/2.0/help none bind,ro 0 0): cannot open directory "/var/lib/snapd": permission denied
update.go:85: cannot change mount namespace according to change mount (/var/lib/snapd/hostfs/usr/share/xubuntu-docs /usr/share/xubuntu-docs none bind,ro 0 0): cannot open directory "/var/lib/snapd": permission denied
Gtk-Message: 00:54:25.889: Failed to load module "xapp-gtk3-module"
Gtk-Message: 00:54:25.890: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
[7138:7138:0204/005427.044188:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.044485:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.044629:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.044771:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.044895:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.045011:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.045136:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.045267:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.045397:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.045719:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.045848:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.045981:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.046123:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.046280:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.046413:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.046548:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.046700:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.046835:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.046966:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.047108:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.047245:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.047378:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.047505:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.047636:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.047767:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.047899:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.048030:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.048166:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.048308:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.048441:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.048572:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.048706:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.048858:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.048991:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.049124:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.049271:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.049402:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.049529:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.049656:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7138:7138:0204/005427.049775:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[7020:7020:0204/005432.519273:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[7143:7148:0204/005432.675086:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005432.772373:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7020:7136:0204/005433.961879:ERROR:udev_watcher.cc(98)] Failed to begin udev enumeration.
[7020:7125:0204/005434.154954:ERROR:cast_crl.cc(402)] CRL - Verification failed.
[7143:7148:0204/005435.575191:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005435.684068:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005437.275347:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005437.364205:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005437.609165:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005437.696343:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005437.984729:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005438.085287:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005438.650339:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005438.756011:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005440.499259:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005440.595362:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005440.682706:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005440.770214:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005443.751371:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005443.852469:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005446.962536:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005447.097901:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005447.118465:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
[7143:7148:0204/005447.241215:ERROR:ssl_client_socket_impl.cc(985)] handshake failed; returned -1, SSL error code 1, net_error -101
Fontconfig error: Cannot load default config file
```

</details>

**Comment by sergio-costas** [comment]
Mmm... Try using "Yaru" instead of "Yaru dark", and set the dark theme in the gnome menu. That way it does work fine for me.

/home/raster/Descargas/gnome-43-confusing-theming-issue-so-dark-or-not-v0-wq5r5jcwt8v91.webp

**Comment by Dan-Master** [comment]
As far as I know, the Dark Mode menu item is a feature of Gnome since version 43.
I have Ubuntu 22.04.1 LTS with an older version of Gnome 42.5 where the menu looks different and there is no possibility to enable the Dark Mode as shown in your screenshot.

![MenuSet](https://user-images.githubusercontent.com/38279872/216968767-3f5e7f7d-844b-428a-952e-7afbc7dd7d64.png)

**Comment by sergio-costas** [comment]
Ops... Ooook...

I'll install a virtual machine and check this.

**Comment by stevebeattie** [comment]
> That connection will be automatic when that version is moved into stable.

Hi @sergio-costas, is there any timeframe for when   will happen? This is still happening on a fully refreshed 22.04 system when logging in via ssh:

```shell
$ lsb_release -sd
Ubuntu 22.04.1 LTS
$ snap list snapd snapd-desktop-integration 
Name                       Version  Rev    Tracking         Publisher   Notes
snapd                      2.58.2   18357  latest/stable    canonical✓  snapd
snapd-desktop-integration  0.1      49     latest/stable/…  canonical✓  -
$ journalctl -n10
Feb 17 12:00:38 sec-jammy-amd64 systemd[1016]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Scheduled restart job, restart counter is at 158.
Feb 17 12:00:38 sec-jammy-amd64 systemd[1016]: Stopped Service for snap application snapd-desktop-integration.snapd-desktop-integration.
Feb 17 12:00:38 sec-jammy-amd64 systemd[1016]: Started Service for snap application snapd-desktop-integration.snapd-desktop-integration.
Feb 17 12:00:39 sec-jammy-amd64 snapd-desktop-i[11519]: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
Feb 17 12:00:39 sec-jammy-amd64 snapd-desktop-integration.snapd-desktop-integration[11519]: Failed to do gtk init
Feb 17 12:00:41 sec-jammy-amd64 systemd[1016]: snap.snapd-desktop-integration.snapd-desktop-integration.service: Scheduled restart job, restart counter is at 159.
Feb 17 12:00:41 sec-jammy-amd64 systemd[1016]: Stopped Service for snap application snapd-desktop-integration.snapd-desktop-integration.
Feb 17 12:00:41 sec-jammy-amd64 systemd[1016]: Started Service for snap application snapd-desktop-integration.snapd-desktop-integration.
Feb 17 12:00:41 sec-jammy-amd64 snapd-desktop-i[11580]: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
Feb 17 12:00:41 sec-jammy-amd64 snapd-desktop-integration.snapd-desktop-integration[11580]: Failed to do gtk init
$ date
Fri Feb 17 12:00:45 PM PST 2023
```

**Comment by sergio-costas** [comment]
@stevebeattie I don't have a precise time frame. But the candidate version does have the fix, and what's better, it autoconnects the login-session-observe, so it should be ready. I'll try to push it today.

**Comment by sergio-costas** [comment]
The candidate version has been promoted to stable, so this should be fixed.
